### ISSUE TITLE
Error in Java FDK while running the list method

### ISSUE THREAD

**Issue by sachin-pikle** [abhirockzz/fn-oci-object-store-workshop#3]
```
Nov 21 22:57:38 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: Exception in thread "main" java.lang.NoSuchMethodError: com.fnproject.fn.api.Headers.canonicalKey(Ljava/lang/String;)Ljava/lang/String;
Nov 21 22:57:38 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.HTTPStreamCodec.readEvent(HTTPStreamCodec.java:296)
Nov 21 22:57:38 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.HTTPStreamCodec.lambda$runCodec$0(HTTPStreamCodec.java:167)
Nov 21 22:57:38 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at org.apache.http.protocol.HttpService.doService(HttpService.java:437)
Nov 21 22:57:38 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:342)
Nov 21 22:57:38 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.HTTPStreamCodec.runCodec(HTTPStreamCodec.java:219)
Nov 21 22:57:38 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.EntryPoint.run(EntryPoint.java:94)
Nov 21 22:57:38 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.EntryPoint.main(EntryPoint.java:43)
Nov 21 23:01:20 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: Exception in thread "main" java.lang.NoSuchMethodError: com.fnproject.fn.api.Headers.canonicalKey(Ljava/lang/String;)Ljava/lang/String;
Nov 21 23:01:20 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.HTTPStreamCodec.readEvent(HTTPStreamCodec.java:296)
Nov 21 23:01:20 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.HTTPStreamCodec.lambda$runCodec$0(HTTPStreamCodec.java:167)
Nov 21 23:01:20 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at org.apache.http.protocol.HttpService.doService(HttpService.java:437)
Nov 21 23:01:20 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at org.apache.http.protocol.HttpService.handleRequest(HttpService.java:342)
Nov 21 23:01:20 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.HTTPStreamCodec.runCodec(HTTPStreamCodec.java:219)
Nov 21 23:01:20 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.EntryPoint.run(EntryPoint.java:94)
Nov 21 23:01:20 linuxkit-00001702ac21 app_id=ocid1.fnapp.oc1.phx.aaaaaaaaagyg7suol3nt3oo24ka3i4uzt7bjf: 	at com.fnproject.fn.runtime.EntryPoint.main(EntryPoint.java:43)
```

**Comment by sachin-pikle** [comment]
fdk version should be 1.0.75 in pom.xml fixed by PR
